data_path: data/processed_data/bitcoin/bitcoin_final_with_embeddings_lag_3.csv
date_column: Date
numeric_features:
  - Open_lag1
  - Open_lag2
  - Open_lag3
  - High_lag1
  - High_lag2
  - High_lag3
  - Low_lag1
  - Low_lag2
  - Low_lag3
  - Close_lag1
  - Close_lag2
  - Close_lag3
  - Adj_Close_lag1
  - Adj_Close_lag2
  - Adj_Close_lag3
target_column: Adj_Close
embedding_columns:
  - embedding_summary_gpt-5-mini_lag1
  - embedding_summary_gpt-5-mini_lag2
  - embedding_summary_gpt-5-mini_lag3
